Add manual testing for sort and edit DG, UG
AY2425S1-CS2103T-W13-1/tp pull request #186
Opened 2024-11-09 12:57 UTC by miuna9890

2024-11-09 23:02 UTC, haleemairfan approved these changes
Looks good!

2024-11-10 16:12 UTC, yyueyii requested changes

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +* 2a. User enters invalid field.
i think this is 1b. ? since it will happen after step 1

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +    - 2a1. Cher detects error in user input and shows correct input format. <br>
this 1c. ?

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +   - add n/anna s/f r/parent p/23456 a/Jurong e/sutd@dfsh.dsfvc  t/tag1
phone numbers need to be 8 digits long

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +      Contact entries will show list sorted in case-insensitive order based on ASCII value of each character in
Maybe can mention that all parents will be sorted before students?

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +    2. Test case: `sort name` <br>
Test case shld be sort address

2024-11-10 16:12 UTC, yyueyii commented on docs/DeveloperGuide.md
> +    2. Test case: `sort k` <br>
Maybe mention that contact entries will not be rearranged/remain unchanged

2024-11-10 16:12 UTC, yyueyii commented on docs/UserGuide.md
> +**Add** | `add n/NAME s/SEX r/ROLE p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…​` <br> e.g., `add n/James Ho r/student p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/Secondary 1`
The example is missing the sex field

2024-11-10 16:13 UTC, yyueyii commented on docs/DeveloperGuide.md
> +    - 1a1. Cher detects error in user input and shows correct input format.
Missing Use case ends

2024-11-11 12:53 UTC, yyueyii approved these changes
LGTM!

2024-11-11 14:09 UTC, merged