Update UG for delete and find commands
AY2425S1-CS2103T-W13-1/tp pull request #212
Opened 2024-11-10 08:02 UTC by haleemairfan

2024-11-10 15:04 UTC, MinkhantEain approved these changes
LGTM.

2024-11-10 15:57 UTC, yyueyii requested changes
Some minor errors, otherwise lgtm!

2024-11-10 17:17 UTC, yyueyii commented on docs/UserGuide.md
> +- `list` followed by `delete 98765432` deletes the person with the phone number `98765432` in the list.
`delete p/98765432`

2024-11-11 12:43 UTC, yyueyii approved these changes
LGTM!

2024-11-11 13:38 UTC, merged